# 爬行者变成彩纸爬行者的概率百分比 / Probability percentage for creeper to become confetti creeper
confetti_chance: 100

# 插件语言设置 / Plugin language setting
# 可选值: zh(简体中文), zht(繁体中文), ja(日语), fr(法语), ru(俄语), ko(韩语), en(英语), es(西班牙语), de(德语), it(意大利语), pt(葡萄牙语), ar(阿拉伯语), hi(印地语), tr(土耳其语), nl(荷兰语), pl(波兰语), sv(瑞典语), th(泰语)
# Available values: zh(Simplified Chinese), zht(Traditional Chinese), ja(Japanese), fr(French), ru(Russian), ko(Korean), en(English), es(Spanish), de(German), it(Italian), pt(Portuguese), ar(Arabic), hi(Hindi), tr(Turkish), nl(Dutch), pl(Polish), sv(Swedish), th(Thai)
# 如果留空或设置为auto，则自动根据服务器地区检测语言
# If left blank or set to auto, the language will be automatically detected based on the server's region
language: auto

confetti_effect:
  # 烟花效果配置 / Firework effect configuration
  - ==: Firework
    # 是否闪烁 / Whether to flicker
    flicker: true
    # 是否有轨迹 / Whether there is a trail
    trail: false
    # 颜色列表 / Color list
    colors:
      - ==: Color
        ALPHA: 255
        RED: 255
        BLUE: 0
        GREEN: 0
      - ==: Color
        ALPHA: 255
        RED: 255
        BLUE: 0
        GREEN: 255
    # 渐变颜色列表 / Fade color list
    fade-colors: []
    # 烟花类型 (BALL-球形) / Firework type (BALL-spherical)
    type: BALL